# Generated by Django 2.2.14 on 2020-11-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='clases',
            new_name='clase',
        ),
    ]
